### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by PLUCS2** [devNahuelOper/DenizenConfidant-#1]
- [x] User auth should have demo login as a feature 
- [x] Third MVP should be making events 
- [x] Fourth MVP is creating artist page 
- [x] Fifth MVP is searching events and artists (by genre, dates, geographic profile, etc.) 
- [x] Sixth MVP Will be production readMe 
- [x] Bonuses can be following artists, etc.

**Comment by devNahuelOper** [comment]
Thanks for these notes!
