### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [devNahuelOper/DenizenConfidant-#2]
- [x] User table needs username, first name, last name, default region, language, birthday, and gender columns
- [x] What is the `performance` column on `Artist`? 
- [x] Artist table should have a `user_id` to connect the artist to the user that made the profile 
- [x] Tracks and albums will be a bonus feature (not part of the create artist MVP) 
- [x] Tracks don't need an artist_id (or a genre_id) if those are decided by the album they belong to?
- [x] Add a `location` column to the `Events` table
- [x] Venues will be a bonus feature 
- [x] Add a bookings table with an `event_id` and `user_id`

**Comment by devNahuelOper** [comment]
for performance I meant to say a column of any upcoming/past shows the artist has. I changed it to upcoming events for now, though totally willing to change it again if you think of something better. maybe even just calling it events or indexing with event_id like I have with genre?

**Comment by PLUCS2** [comment]
- [ ] Take out the upcoming events column - this can be accessed by a joins table
